import { z } from "zod";

export const CURRENT_OUTCOME_RECONCILIATION_VERSION = 2;

export const learningAssetSchema = z.enum(["SOL", "ETH", "BTC"]);

export const scalpSetupTypeSchema = z.enum([
  "range-reversal",
  "liquidity-sweep",
  "v-reversal",
  "double-reversal",
]);

export const tradeLearningOutcomeSchema = z.object({
  outcomeId: z.string().trim().min(1),
  episodeId: z.string().trim().min(1).optional(),
  reconciliationVersion: z.number().int().positive().optional(),
  trainingEligible: z.boolean().optional(),
  trainingExclusionReason: z.string().trim().min(1).nullable().optional(),
  walletAddress: z.string().trim().min(1),
  executionId: z.string().trim().min(1),
  decisionId: z.string().trim().min(1).nullable(),
  signalId: z.string().trim().min(1),
  asset: learningAssetSchema,
  side: z.enum(["long", "short"]),
  openedAt: z.string().datetime(),
  closedAt: z.string().datetime(),
  positionPubkey: z.string().trim().min(1).nullable(),
  entryPrice: z.number().finite().positive().nullable(),
  exitPrice: z.number().finite().positive().nullable(),
  collateralUsd: z.number().finite().positive(),
  sizeUsd: z.number().finite().positive(),
  leverage: z.number().finite().positive(),
  takeProfitPrice: z.number().finite().positive().nullable(),
  stopLossPrice: z.number().finite().positive().nullable(),
  grossPnlUsd: z.number().finite(),
  feesUsd: z.number().finite().min(0),
  netPnlUsd: z.number().finite(),
  returnOnCollateralPercent: z.number().finite(),
  durationMinutes: z.number().finite().min(0),
  exitReason: z.enum(["take-profit", "stop-loss", "liquidation", "manual", "unknown"]),
  signalConfidence: z.number().finite().min(0).max(1).nullable(),
  signalType: z.enum(["trend", "breakout", "scalp"]).nullable(),
  trendWindow: z.number().finite().min(1).nullable(),
  trendThreshold: z.number().finite().min(0).nullable(),
  breakoutPercent: z.number().finite().min(0).nullable(),
  cooldownSeconds: z.number().finite().min(0).nullable(),
  trendStrengthPercent: z.number().finite().nullable(),
  breakoutStrengthPercent: z.number().finite().nullable(),
  volatilityPercent: z.number().finite().min(0).nullable(),
  atrPercent: z.number().finite().min(0).nullable(),
  indicatorScore: z.number().finite().min(0).nullable().optional(),
  emaSpreadPercent: z.number().finite().nullable().optional(),
  emaSlopePercent: z.number().finite().nullable().optional(),
  rsi: z.number().finite().nullable().optional(),
  macdHistogram: z.number().finite().nullable().optional(),
  macdHistogramChange: z.number().finite().nullable().optional(),
  adx: z.number().finite().nullable().optional(),
  plusDi: z.number().finite().nullable().optional(),
  minusDi: z.number().finite().nullable().optional(),
  volumeRatio: z.number().finite().nullable().optional(),
  bollingerBandwidthPercent: z.number().finite().nullable().optional(),
  bollingerPosition: z.number().finite().nullable().optional(),
  scalpSetupType: scalpSetupTypeSchema.nullable().optional(),
  priceActionScore: z.number().finite().min(0).max(1).nullable().optional(),
  priceActionTags: z.array(z.string().trim().min(1)).optional(),
  trendBias: z.enum(["bullish", "bearish", "sideways"]).nullable(),
  createdAt: z.string().datetime(),
});

export const learningValidationSchema = z.object({
  sampleSize: z.number().int().min(0),
  trainingSize: z.number().int().min(0),
  validationSize: z.number().int().min(0),
  winRate: z.number().finite().min(0).max(1),
  expectancyUsd: z.number().finite(),
  profitFactor: z.number().finite().min(0),
  maxDrawdownUsd: z.number().finite().min(0),
  passed: z.boolean(),
  reasons: z.array(z.string()),
});

export const scalpLearningProfileSchema = z.object({
  policyVersion: z.number().int().positive().default(1),
  policyOutcomeOffset: z.number().int().min(0).default(0),
  learnedFromClosedTrades: z.number().int().min(0),
  minimumConfidence: z.number().finite().min(0.55).max(0.85),
  cooldownSeconds: z.number().int().min(300).max(7_200),
  longRsiMaximum: z.number().finite().min(30).max(65),
  shortRsiMinimum: z.number().finite().min(35).max(70),
  longBollingerMaximum: z.number().finite().min(-0.25).max(0.45),
  shortBollingerMinimum: z.number().finite().min(0.55).max(1.25),
  maximumAdx: z.number().finite().min(12).max(40),
  maximumEmaSpreadPercent: z.number().finite().min(0.1).max(1.5),
  minimumAtrPercent: z.number().finite().min(0.005).max(1),
  minimumBandwidthPercent: z.number().finite().min(0.02).max(3),
  minimumVolumeRatio: z.number().finite().min(0.5).max(2),
  minimumPriceActionScore: z.number().finite().min(0.45).max(0.85),
  strongReversalScore: z.number().finite().min(0.6).max(0.95),
  minimumSweepPercent: z.number().finite().min(0.01).max(1),
  minimumReclaimPercent: z.number().finite().min(0.02).max(2),
  setupConfidenceAdjustments: z.object({
    rangeReversal: z.number().finite().min(-0.08).max(0.15),
    liquiditySweep: z.number().finite().min(-0.08).max(0.15),
    vReversal: z.number().finite().min(-0.08).max(0.15),
    doubleReversal: z.number().finite().min(-0.08).max(0.15),
  }),
  riskMultiplier: z.number().finite().min(0.5).max(1),
  preferredDirection: z.enum(["bullish", "bearish", "balanced"]),
  consecutiveLosses: z.number().int().min(0).max(5),
  validation: learningValidationSchema,
});

const learnedAssetAdjustmentSchema = z.object({
  trendThreshold: z.number().finite().min(0.01).max(10),
  breakoutPercent: z.number().finite().min(0.01).max(8),
  leverageMultiplier: z.number().finite().min(0.5).max(1.25),
  allocationMultiplier: z.number().finite().min(0.5).max(1.1),
});

export const decisionLearningProfileSchema = z.object({
  profileId: z.string().trim().min(1),
  walletAddress: z.string().trim().min(1),
  version: z.number().int().positive(),
  status: z.enum(["active", "candidate", "archived"]),
  source: z.enum(["operator-baseline", "automatic", "manual-training"]),
  createdAt: z.string().datetime(),
  promotedAt: z.string().datetime().nullable(),
  learnedFromClosedTrades: z.number().int().min(0),
  outcomeDataVersion: z.number().int().positive().optional(),
  strategyBaselineVersion: z.number().int().positive().optional(),
  minimumConfidence: z.number().finite().min(0.45).max(0.82),
  leverageFloor: z.number().finite().min(1).max(125).optional(),
  leverageCap: z.number().finite().min(1).max(125),
  leverageQualityExponent: z.number().finite().min(0.5).max(4).optional(),
  leverageVolatilityPenalty: z.number().finite().min(0).max(3).optional(),
  leverageLossStepdown: z.number().finite().min(0.5).max(1).optional(),
  consecutiveLosses: z.number().int().min(0).max(3).optional(),
  maximumAllocationPercent: z.number().finite().min(1).max(100),
  targetWalletRiskPercent: z.number().finite().min(0.1).max(10),
  preferredDirection: z.enum(["bullish", "bearish", "balanced"]),
  trendWindow: z.number().int().min(5).max(180),
  cooldownSeconds: z.number().int().min(30).max(86_400),
  takeProfitRoePercent: z.number().finite().min(0).max(50),
  stopLossRoePercent: z.number().finite().min(0).max(50),
  minimumRewardRiskRatio: z.number().finite().min(1).max(4),
  atrLookback: z.number().int().min(7).max(30),
  atrStopMultiplier: z.number().finite().min(1).max(3),
  volatilityCeilingPercent: z.number().finite().min(1.5).max(10),
  indicatorSettings: z.object({
    longRsiMin: z.number().finite().min(35).max(60),
    longRsiMax: z.number().finite().min(60).max(75),
    shortRsiMin: z.number().finite().min(25).max(40),
    shortRsiMax: z.number().finite().min(40).max(60),
    minimumAdx: z.number().finite().min(15).max(30),
    minimumVolumeRatio: z.number().finite().min(0.8).max(1.4),
    minimumScore: z.number().finite().min(2).max(5),
  }).optional(),
  scalpProfile: scalpLearningProfileSchema.optional(),
  assetAdjustments: z.object({
    SOL: learnedAssetAdjustmentSchema,
    ETH: learnedAssetAdjustmentSchema,
    BTC: learnedAssetAdjustmentSchema,
  }),
  validation: learningValidationSchema,
  summary: z.string().trim().min(1),
});

export type TradeLearningOutcome = z.infer<typeof tradeLearningOutcomeSchema>;
export type DecisionLearningProfile = z.infer<typeof decisionLearningProfileSchema>;
export type ScalpLearningProfile = z.infer<typeof scalpLearningProfileSchema>;
export type ScalpSetupType = z.infer<typeof scalpSetupTypeSchema>;
export type LearningAsset = z.infer<typeof learningAssetSchema>;
